### ISSUE TITLE
Stochastic Dynamic Dual Programming

### ISSUE THREAD

**Issue by blegat** [joehuchette/StructJuMP.jl#10]
Can we do [Stochastic Dynamic Dual Programming](http://www.optimization-online.org/DB_FILE/2009/12/2509.pdf) using StochJuMP ?

**Comment by kibaekkim** [comment]
@blegat SDDP is a "method", whereas StochJuMP provides a "modeling" interface.

**Comment by blegat** [comment]
As I understand it, SDDP and Benders are two methods to solve Stochastic Programs.
It seems that StochJuMP includes a Benders solver. So I thought, why not SDDP.
Anyway, if StochJuMP.jl is not the place for adding a solver, do you think it is possible to use a separate SDDP solver using StochJuMP as modeling interface ?

**Comment by blegat** [comment]
Even if it is not implemented, do you think it would make sense to add this (possibly in a separate package) ? So that someone would model its stochastic program and then could choose to solve it between Bender and SDDP.

**Comment by mlubin** [comment]
@blegat yes, if SDDP input format is analogous to the Benders input format, then you could definitely have SDDP as an option for a solution method

**Comment by blegat** [comment]
I have implemented SDDP in a separate package : https://github.com/blegat/StochasticDualDynamicProgramming.jl :)
